name = "GT6 Lite"
author = "RoBaertschi"
version = "1.0.0"
description = "A simple GT6 minecraft modpack based"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dbaa6abebc7928d8e6ef844fa45ec2abfa323e754751560f86241ce910f55c80"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
