name = "GT6 Lite"
author = "RoBaertschi"
version = "1.0.0"
description = "A simple GT6 minecraft modpack based"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acae17eb97cf634016ef19c5766d6076df34bad3cd3d592bd905e175fb40e4eb"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
